export const STATUS = {
  IDLE: "idle",
  CALL: "in_call",
};

export const EVENTS = {
  CALLING_USER: "CALLING_USER",
  INCOMING_CALL: "INCOMING_CALL",
  CALL_ANSWERED: "CALL_ANSWERED",
  UPDATE_USER_STATUS: "UPDATE_USER_STATUS",
  CALL_DISCONNECT: "CALL_DISCONNECT",
  USER_LEFT: "USER_LEFT",
  SOCKET_DISCONNECT: "SOCKET_DISCONNECT",
  CALL_REJECTED: "CALL_REJECTED",
};
